[package]
name = "app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lib = { path = "../lib" }
riscv = { git = "https://github.com/rcore-os/riscv", features = ["inline-asm"] }
